config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/edit'

  get 'categories/update'

  get 'categories/destroy'

root to: 'pages#home'
get '/salut(/:name)', to: 'pages#salut', as:'salut'
resources :posts
resources :categories
resources :pizzas
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :metas, as: :metaable
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_validation :set_default_slug, on: [:create, :update], if: '!slug.nil?'

    private
    def set_default_slug
      if !self.name.nil? && !self.slug.nil? && (!self.name.empty? && self.slug.empty?)
        self.slug = name.parameterize
      end
    end
  end

end

app/models/meta.rb
class Meta < ActiveRecord::Base
  belongs_to :metaable, polymorphic: true
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  include Sluggable;

  belongs_to :category, counter_cache: true
  has_and_belongs_to_many :tags
  has_many :metas, as: :metaable

  scope :online, -> { where(online: true) }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/validators/name_validator.rb
class NameValidator < ActiveModel::Validator
  def validate(record)

    if record.name.nil? || record.name.length != 2
      record.errors.add(:name, :not_2, {message:'Field must be 2 caracters long'})
    end
    if record.name.nil? || record.name.length != 2
      record.errors.add(:content, 'Field must be 2 caracters long')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  def index
    @session = session[:user_id]
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.create(category_params)
    redirect_to category_path(category.id)
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to categories_path

  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def salut
    @name = params[:name]
  end

  def home
  end

end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]
  def index
    @pizzas = Pizza.all
  end

  def show
  end

  def new
    @pizza = Pizza.new
  end

  def create
    pizza = Pizza.create(pizza_params)
    redirect_to pizzas_path
  end

  def edit
  end

  def update
    @pizza.update(pizza_params)
    redirect_to pizzas_path
  end

  def destroy
    @pizza.destroy
    redirect_to pizzas_path
  end

  private
  def pizza_params
    params.require(:pizza).permit(:name, :description)
  end

  def set_pizza
    @pizza = Pizza.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  include GravatarHelper

  def index
    @posts = Post.includes(:category, :tags).all
    respond_to do |format|
      format.html
      format.json {render json: @posts.as_json(only: [:name, :created_at, :id])}
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post.valid?
      post.save
      flash[:notice] = "Post successfully created"
      redirect_to posts_path
    else
      @post = post
      render 'new'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post successfully deleted"
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:name, :content, :slug, :category_id)
    end

    def set_post
      @post = Post.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gravatar_helper.rb
module GravatarHelper

  def gravatar(email, options = {s:200})
    throw TypeError unless email.respond_to?(:to_s)
    image_tag "https://gravatar.com/avatar/#{Digest::MD5.hexdigest(email.to_s)}?s=#{options[:s]}"
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit the category</h2>
<%= form_for @category do |f| %>
<div class="form-group">
  <%= f.text_area :name, class:'form-control', placeholder:'Name'%>
</div>
<div class="form-group">
  <%= f.text_area :slug, class:'form-control', placeholder:'Url'%>
</div>
<div class="form-group">
<button type="submit" class="btn btn-success">Save changes </button>
</div>
<% end %>

app/views/categories/index.html.erb
<h2>Categories Page</h2>

<table class="table">
  <thead>
    <tr>
      <td>ID</td>
      <td>NAME</td>
      <td>ACTIONS</td>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <tr>
    <td>
      <%= category.id %>
    </td>
    <td>
      <%= category.name %>
    </td>
    <td>
      <a href=" <%= edit_category_path(category.id) %>" class="btn btn-primary">Edit</a>
      <a href=" <%= category_path(category.id) %>" class="btn btn-primary">See</a>
      <a href=" <%= category_path(category.id) %>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>

<p>
  <a href=" <%= new_category_path %>" class="btn btn-success">
    Create new category</a>
</p>

app/views/categories/new.html.erb
<h3>New category</h3>

<%= form_for @category do |f| %>
<div class="form-group">
  <%= f.text_area :name, class:'form-control', placeholder: 'Name' %>
</div>
<div class="form-group">
<%= f.text_area :slug, class:'form-control', placeholder: 'Url' %>
</div>
<div class="btn btn-primary">
<button type="submit">Create the category</button>
</div>
<% end %>

app/views/categories/show.html.erb
<h3> <%= @category.name %> </h3>
<p><a href="<%=categories_path%>" class="btn btn-primary">Back to categories</a></p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'RoR Formation'%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="<%= root_path %>">testApp</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= categories_path %>">Categories
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Posts
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pizzas_path %>">Pizzas
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </nav>

      <div class="container" style="padding-top: 5rem">
        <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
        <% end %>
        <%= yield %>
        <%= yield(:sidebar) %>
      </div>

    </body>
  </html>

app/views/layouts/sidebar.html.erb
<div class="row">
  <% if content_for?(:sidebar) %>
  <div class="col-sm-8">
    <%= yield(:content) %>
  </div>
  <div class="col-sm-4">
    <%= yield(:sidebar) %>
  </div>
  <% else %>
  <div class="col-sm-12">
  <%= yield(:content) %>
</div>
  <%end%>
</div>

app/views/pages/home.html.erb
<h1>Welcome to the testApp </h1>
<p>You better try it yourself, motherfucker </p>

app/views/pages/salut.html.erb
<h2> Salut <%= @name %> le moche </h1> <%= 1+1 %>

app/views/pizzas/edit.html.erb
<h3>Edit your pizza</h3>

<%= form_for @pizza do |f| %>
<div class="form-group">
<%= f.text_area :name, class:'form-control', placeholder:'Name' %>
</div>
<div class="form-group">
<%= f.text_area :description, class:'form-control', placeholder:'Description' %>
</div>
<div class="form-group">
<button type="submit" class='btn btn-primary'>Save</button>
</div>
<% end %>

app/views/pizzas/index.html.erb
<% @pizzas.each do |pizza| %>
  <h3> <%= pizza.name %> </h3>
  <p> <%= pizza.description %> </p>
  <p>
    <a href="<%= pizza_path(pizza.id) %>" class="btn btn-primary">See</a>
    <a href="<%= edit_pizza_path(pizza.id) %>" class="btn btn-primary">Edit</a>
    <a href="<%= pizza_path(pizza.id) %>" class="btn btn-danger" data-confirm="sure?" data-method="delete">Delete</a>
  </p>
<% end %>

<p><a href="<%= new_pizza_path %>" class="btn btn-success">Create your own pizza</a></p>

app/views/pizzas/new.html.erb
<h3>Create your pizza</h3>

<%= form_for @pizza do |f| %>
<div class="form-group">
<%= f.text_area :name, class:'form-control', placeholder:'Name' %>
</div>
<div class="form-group">
<%= f.text_area :description, class:'form-control', placeholder:'Description' %>
</div>
<div class="form-group">
<button type="submit" class='btn btn-primary'>Save</button>
</div>
<% end %>

app/views/pizzas/show.html.erb
<h3><%= @pizza.name %> </h3>
<p> <%= @pizza.description %> </p>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <% @post.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<%= form_for @post do |f| %>
<div class="form-group">
  <label>Post title</label>
  <%= f.text_field :name, class:'form-control' %>
</div>
<div class="form-group">
  <label>Post URL</label>
  <%= f.text_field :slug, class:'form-control' %>
</div>
<div class="form-group">
  <label for="category">Post Category</label>
  <%= f.select :category_id, Category.pluck(:name, :id) %>
</div>
<div class="form-group">
  <label>Post content</label>
<%= f.text_area :content, class: 'form-control' %>
</div>
<div class="form-group">
  <button type="submit" class="btn btn-primary">Save modifications</button>
</div>
<% end %>

app/views/posts/_post.html.erb
<h3> <%= post.name %> </h3>
<p> <%= post.content %> </p>
<%if post.category %>
<p> <%= post.category.name %></p>
<% end %>
<p>
  Tags:
    <% post.tags.each do |tag| %>
    <%=tag.name %>
      <% end %>
</p>
<%= link_to('See the post', post, class:'btn btn-primary') %>
<%= link_to('Edit the post', [:edit, post], class:'btn btn-success') %>
<%= link_to('Delete the post', post, class:'btn btn-danger', data:{confirm:'Are you sure?', method: :delete}) %>


</p>

app/views/posts/edit.html.erb
<h2>Edit the post</h2>

<%= gravatar('adrienfloor@gmail.com'); %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= render @posts %>  
<br>
<p>
  <a href="<%= new_post_path %>" class="btn btn-primary">New post</a>
</p>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% content_for(:title, @post.name) %>

<% content_for :content do %>

<h3><%= @post.name %></h3>
<p><%= @post.content %></p>
<p>
  <a href="<%= edit_post_path(@post) %>" class="btn btn-success">Edit the post</a>
  <a href="<%= posts_path %>" class="btn btn-primary">Back to posts</a>
</p>

<% end %>

<%= render template: 'layouts/sidebar' %>